import streamlit as st
import pandas as pd
import datetime
from databricks import sql

from .student_OP import get_students_by_department
from FUNC.send_email import send_report_email


# ----------------------------------- SQL Query Run on Databricks----------------

# -------------------------- Fetch attendence data ---------------------------


def get_attendance_from_gold(start_date, end_date, total_working_days):

    query = f"""
    SELECT 
        department_id,
        student_id,
        COUNT(*) AS present_days,
        ROUND(COUNT(*) * 100.0 / {total_working_days}, 2) AS attendance_percentage
    FROM college_dw.gold.fact_attendance
    WHERE attendance_date BETWEEN '{start_date}' AND '{end_date}'
    GROUP BY department_id, student_id
    """

    with sql.connect(
        server_hostname=st.secrets["databricks"]["host"].replace("https://", ""),
        http_path=st.secrets["databricks"]["http_path"],
        access_token=st.secrets["databricks"]["token"]
    ) as conn:

        df = pd.read_sql(query, conn)

    return df




# ------------------------ GENERATE + SEND REPORTS --------------------------




def generate_and_send_reports(attendance_df: pd.DataFrame,
                             selected_departments_info: list,
                             total_working_days: int,
                             start_date: datetime.date,
                             end_date: datetime.date):

    success_count = 0
    fail_count = 0

    month_year_str = start_date.strftime("%B-%Y")

    if total_working_days <= 0:
        st.warning("Total Working Days is zero. Cannot calculate attendance.")
        return 0, len(selected_departments_info)

    for dept_info in selected_departments_info:

        dept_id = dept_info.get('dep_id')
        dept_name = dept_info.get('dep_name', 'Unknown Department')
        hod_email = dept_info.get('dep_hod_mail')

        if not hod_email:
            st.warning(f"Skipping {dept_name}: No HOD email")
            fail_count += 1
            continue

        st.write(f"📊 Processing report for: {dept_name}")

        try:

# ----------------------------------- FETCH STUDENTS ----------------------



            students = get_students_by_department(dept_id)

            if not students:
                st.info(f"No students found in {dept_name}")
                continue

            df_roster = pd.DataFrame(students)


# ------------------------- FILTER DATA ---------------------------------



            df_dept = attendance_df[
                attendance_df["department_id"].astype(str) == str(dept_id)
            ].copy()


# --------------------------- SELECT REQUIRED COLUMNS ---------------------


            df_counts = df_dept[[
                "student_id",
                "present_days",
                "attendance_percentage"
            ]].copy()


# ------------------------------ MERGE WITH STUDENT ROSTER ---------------------


            df_report = pd.merge(
                df_roster,
                df_counts,
                left_on="S_id",
                right_on="student_id",
                how="left"
            )

# ---------------------------- HANDLE NULLS ---------------------------


            df_report["present_days"].fillna(0, inplace=True)
            df_report["attendance_percentage"].fillna(0, inplace=True)

            df_report["present_days"] = df_report["present_days"].astype(int)
            df_report["attendance_percentage"] = df_report["attendance_percentage"].round(2)



# -------------------------- FINAL REPORT FORMAT ---------------------



            df_final = pd.DataFrame({
                "Month-Year": month_year_str,
                "Student ID": df_report["S_id"],
                "Student Name": df_report["S_name"],
                "Department ID": dept_id,
                "Days Present": df_report["present_days"],
                "Attendance %": df_report["attendance_percentage"]
            })

            df_final.sort_values(by="Student Name", inplace=True)


# ------------------------- CONVERT TO HTML -------------------------


            report_html = df_final.to_html(index=False)

            email_body = f"""
            <html>
            <body>
                <h2>Attendance Report - {dept_name}</h2>
                <p><b>Period:</b> {start_date.strftime('%d %b %Y')} to {end_date.strftime('%d %b %Y')}</p>
                <p><b>Total Working Days:</b> {total_working_days}</p>
                <hr>
                {report_html}
                <hr>
                <p><i>Generated by Attendance System</i></p>
            </body>
            </html>
            """

            subject = f"Attendance Report: {dept_name} ({month_year_str})"



# ----------------------------- SEND EMAIL ------------------------



            sent, msg = send_report_email(hod_email, subject, email_body)

            if sent:
                st.success(f" Report sent to {hod_email}")
                success_count += 1
            else:
                st.error(f" Failed for {dept_name}: {msg}")
                fail_count += 1

        except Exception as e:
            st.error(f"Error processing {dept_name}: {e}")
            fail_count += 1

    return success_count, fail_count